### ISSUE TITLE
Criação do Banco de Dados

### ISSUE THREAD

**Issue by goisjulia** [codenation-dev/squad-2-c-sharp-easynvest-1#10]
**Objetivo:** Realizar a criação do Banco de Dados da Central de Erros com a criação das tabelas, chaves primárias e estrangeiras e os relacionamentos para que as funções das classes sejam implementadas.

**Comment by leeserpa** [comment]
Pessoal, fiz algumas alterações que achei necessário na criação do banco e tabelas. Qualquer dúvida, me avisem.
[script de criacao do banco.zip](https://github.com/codenation-dev/squad-2-c-sharp-easynvest-1/files/3838879/script.de.criacao.do.banco.zip)

**Comment by leeserpa** [comment]
Novo script atualizado
[script de criacao do banco.zip](https://github.com/codenation-dev/squad-2-c-sharp-easynvest-1/files/3889466/script.de.criacao.do.banco.zip)
