### ISSUE TITLE
Enviar foto e minicurrículo

### ISSUE THREAD

**Issue by LiliaMatos** [codenation-dev/squad-2-c-sharp-easynvest-1#7]
**Objetivo:** Todas as integrantes da squad devem anexar uma foto e um mini currículo para adição no template da apresentação do projeto final.

**Comment by Wandercilia** [comment]
Possuo quase 25 anos de experiência na área de TI, grande parte deles atuando em análise e desenvolvimento de aplicações em Oracle Pl/Sql. Atualmente estou em fase de finalização (entrega de TCC) de uma especialização em Ciência de Dados.
![IMG-20181111-WA0040](https://user-images.githubusercontent.com/51337792/67820049-71a22180-fa96-11e9-979b-aa44b98f9894.jpg)

**Comment by goisjulia** [comment]
Sou estudante de bacharelado de Sistemas de Informação e atualmente sou estagiária front-end no Banco do Brasil. Me formo em 2020 e já fiz um curso técnico de informática em que tive contato com várias linguagens de programação.


![P_20181225_002715_HDR_p 1](https://user-images.githubusercontent.com/33931791/67903083-7d025500-fb49-11e9-8a24-e31b4a3ef640.jpg)

**Comment by ana-souza** [comment]
Estudo Sistemas de Informação na Universidade de São Paulo e sou estagiária na OLX Brasil, atuando com suporte técnico e funcional. Tenho experiência acadêmica com linguagens orientadas a objetos e atualmente busco oportunidade como desenvolvedora de software. 
 
![55760025_2803125679757660_6946873141855518720_o](https://user-images.githubusercontent.com/35928158/68072251-6daa2400-fd62-11e9-9ec3-e483b711c9df.jpg)

**Comment by Jessicans** [comment]
![mini curriculo](https://user-images.githubusercontent.com/54457937/68533970-1bdb3e00-030e-11ea-9c2d-61f6b951913b.jpg)

**Comment by leeserpa** [comment]
Sou formada em Ciência da Computação pela Anhembi Morumbi, possuo quase quatro anos de experiência em programação back-end e banco de dados SQL Server. Atualmente trabalho como Programadora em uma empresa de Software para Compliance.

![IMG_1568](https://user-images.githubusercontent.com/34216854/68723421-4a1f7e80-0597-11ea-8eb5-4d97ba35dde8.JPG)

**Comment by LiliaMatos** [comment]
[ApresentaçãoProjetoFinal.pptx](https://github.com/codenation-dev/squad-2-c-sharp-easynvest-1/files/3852215/ApresentacaoProjetoFinal.pptx)

Olá garotas, segue a apresentação com os currículos atualizados, vejam se está ok para vcs.
bjos
